<?xml version="1.0"?>
<package format="2">
    <name>robotont_gazebo</name>
    <version>0.0.3</version>
    <description>The robotont_gazebo package</description>

    <maintainer email="veiko.vunder@ut.ee">Veiko Vunder</maintainer>
    <maintainer email="karl.kruusamae@ut.ee">Karl Kruusamäe</maintainer>

    <url type="website">https://wiki.ros.org/robotont</url>
    <url type="website">https://robotont.ut.ee</url>
    <url type="repository">https://github.com/robotont/robotont_gazebo</url>

    <license>Apache 2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    <build_depend>rclcpp</build_depend>
    <build_depend>ros_gz_sim</build_depend>

    <exec_depend>robotont_description</exec_depend>
    <exec_depend>robotont_nuc_description</exec_depend>
    <exec_depend>rclcpp</exec_depend>
    <exec_depend>ros_gz_sim</exec_depend>
    <exec_depend>ros_gz_bridge</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
        <gazebo_ros gazebo_media_path="${prefix}"/>
    </export>
</package>
