local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 0.5
  publish_frequency: 2
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.02
  inflation_radius: 0.1



plugins: 
#- {name: static_layer, type: "costmap_2d::StaticLayer"} 
- {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}