obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
resolution: 0.02

obstacle_layer:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

static_layer:
  map_topic: map
  lethal_cost_threshold: 100
