global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 0.5
  static_map: true
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.02
  inflation_radius: 0.1

plugins: 
- {name: static_layer, type: "costmap_2d::StaticLayer"} 
- {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}